name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        run: |
          echo CMOCKA_INSTALL="${HOME}/builds/cmocka-install" >> "${GITHUB_ENV}"
          ./ci/before_install.sh
      - name: Install more prerequisites
        run: ./ci/install.sh cmocka libnereon
      - name: Configure
        run: |
          ./autogen.sh
          ./configure --enable-tests
      - name: Build
        run: ./ci/main.sh
