name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  LOGNAME: "GitHub_Action" # TODO: needed? orig. from travis ci

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        run: ./ci/before_install.sh
      - name: Install more prerequisites
        run: ./ci/install.sh
      - name: Configure
        run: |
          ./autogen.sh
          ./configure --enable-tests
      - name: Build
        run: ./ci/main.sh
      - name: Check patch
        run: ./ci/checkpatch.sh
