name: Windows

on:
  push:
    branches:
      - main
      - 'release/**'
    paths-ignore:
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - '*.sh'
      - '.*'
      - 'Brewfile'
      - '_*'
      - 'doc/**'
      - 'flake.lock'
      - 'nix/**'
      - '.cirrus.yml'
      - '.github/workflows/*.yml'
      - '!.github/workflows/windows.yml'
      - 'ci/before_install/*'
      - '!ci/before_install/msys.sh'
      - 'ci/checkpatch*'
  pull_request:
    paths-ignore:
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - '*.sh'
      - '.*'
      - 'Brewfile'
      - '_*'
      - 'doc/**'
      - 'flake.lock'
      - 'nix/**'
      - '.github/workflows/*.yml'
      - '!.github/workflows/windows.yml'
      - 'ci/before_install/*'
      - '!ci/before_install/msys.sh'
      - 'ci/checkpatch*'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        retrace-test: [v1, v2, v2wrapper]
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: msys2/setup-msys2@v2
        with:
          path-type: strict
          update: false

      - name: Install more prerequisites
        run: |
          ./ci/before_install.sh
          ./ci/install.sh libnereon

      - name: Build
        run: ./ci/main.sh ${{ matrix.retrace-test }}
